### ISSUE TITLE
Can't load javascript from browser

### ISSUE THREAD

**Issue by bradphelan** [dotnet-websharper/suave#7]
See this thread on stackoverflow and the comments

http://stackoverflow.com/questions/34018684/how-to-get-basic-websharper-app-in-xamarin-loading-javascript-in-browser

**Comment by Tarmil** [comment]
Indeed it seems the script resources don't get extracted to `Scripts/WebSharper/` like they should. I'm investigating.

**Comment by Tarmil** [comment]
[I just fixed this issue upstream in websharper](https://github.com/intellifactory/websharper/commit/d829ad845b0c96ea15b04c751ab986eda5e0e7d2), so this will be working correctly as soon as we publish to NuGet.

As a workaround in the meantime, you can add an empty `Web.config` file to your project, that should trick WebSharper into extracting the resource files.

**Comment by bradphelan** [comment]
Thanks for fixing it :) I hope I have another rainy afternoon sometime soon
to try it again. it seems like a really nice tool.
