### ISSUE TITLE
Request hangs if doesn't match a sitelet URL

### ISSUE THREAD

**Issue by endeavour** [dotnet-websharper/suave#9]
Reproduction:

1) Create a new websharper suave project
2) Point the browser at a URI that doesn't exist (e.g. http://localhost:8083/foo)

The brower will just freeze until it times out because the server never replies to the request.

Expected behaviour: URIs that don't match sitelets, RPC calls etc should pass through to the next item in the suave pipeline.

**Comment by ademar** [comment]
You need to provide a catch-all route as last route

``` fsharp
let app = choose [ yada; yada; NOT_FOUND "file not found" ]
```

**Comment by ademar** [comment]
Hum .. so you mean it does not reach `NOT_FOUND` in the above code ?

**Comment by endeavour** [comment]
Yes exactly, if you do something like:
`choose [WebSharperAdapter.ToWebPart mySitelet; NOT_FOUND "file not found"]`

Then hit a URL that doesn't exist, the request freezes rather than returning a 404.

**Comment by boechat107** [comment]
Is there some update on this subject?

**Comment by ademar** [comment]
This should be working now as per our latest pre-release v2.0.0-alpha6.
